export const EXPENSE_CATEGORIES = [
  'Food & Dining',
  'Transportation',
  'Housing',
  'Utilities',
  'Health',
  'Shopping',
  'Entertainment',
  'Savings',
  'Education',
  'Travel',
  'Personal Care',
  'Gifts & Donations',
  'Investments',
  'Debt',
  'Loans',
  'Others'
];

export const INCOME_CATEGORIES = [
  'Salary',
  'Freelance',
  'Business',
  'Investment',
  'Allowance',
  'Gift',
  'Rental',
  'Refunds',
  'Other'
];

export const COMMON_DESCRIPTIONS = [
  'Groceries', 
  'Rent', 
  'Electricity Bill', 
  'Water Bill', 
  'Internet Bill', 
  'Mobile Load', 
  'Gasoline / Fuel', 
  'Commute / Fare', 
  'Lunch', 
  'Dinner', 
  'Coffee', 
  'Snacks', 
  'Online Shopping',
  'Medicine', 
  'Tuition Fee', 
  'School Supplies', 
  'Gym Membership', 
  'Loan Payment', 
  'Credit Card Payment', 
  'Salary', 
  'Freelance Payment', 
  'Allowance'
];

export const DEFAULT_QUICK_LINKS = [
  { id: 'yt', title: 'YouTube', url: 'https://youtube.com', color: 'bg-red-500' },
  { id: 'fb', title: 'Facebook', url: 'https://facebook.com', color: 'bg-blue-600' },
  { id: 'gm', title: 'Gmail', url: 'https://mail.google.com', color: 'bg-red-400' },
  { id: 'sp', title: 'Spotify', url: 'https://open.spotify.com', color: 'bg-green-500' },
];

export const APP_BACKGROUNDS = {
  default: {
    label: 'Minimal',
    className: 'bg-slate-50 dark:bg-slate-950'
  },
  ocean: {
    label: 'Ocean',
    className: 'bg-gradient-to-br from-cyan-50 to-blue-100 dark:from-slate-900 dark:to-cyan-950'
  },
  sunset: {
    label: 'Sunset',
    className: 'bg-gradient-to-br from-orange-50 to-rose-100 dark:from-slate-900 dark:to-rose-950'
  },
  forest: {
    label: 'Forest',
    className: 'bg-gradient-to-br from-emerald-50 to-teal-100 dark:from-slate-900 dark:to-emerald-950'
  },
  royal: {
    label: 'Royal',
    className: 'bg-gradient-to-br from-indigo-50 to-purple-100 dark:from-slate-900 dark:to-indigo-950'
  },
  midnight: {
    label: 'Midnight',
    className: 'bg-gradient-to-br from-slate-200 to-gray-300 dark:from-slate-950 dark:to-black'
  }
};

export const TRANSLATIONS = {
  en: {
    goodMorning: 'Good Morning',
    goodAfternoon: 'Good Afternoon',
    goodEvening: 'Good Evening',
    quickAccess: 'Quick Access',
    customize: 'Customize',
    done: 'Done',
    dailyReminders: 'Daily Reminders',
    addTask: 'Add a new task...',
    supportDev: 'Support the Developer',
    budgetPlanner: 'Budget Planner',
    addTransaction: 'Add Transaction',
    income: 'Income',
    expense: 'Expense',
    description: 'Description',
    amount: 'Amount',
    date: 'Date',
    category: 'Category',
    addRecord: 'Add Record',
    updateRecord: 'Update Record',
    cancel: 'Cancel',
    actions: 'Actions',
    totalBalance: 'Total Balance',
    spendingHealth: 'Spending Health',
    linkVault: 'Smart Link Vault',
    searchLinks: 'Search saved links...',
    save: 'Save',
    dashboard: 'Dashboard',
    vault: 'Link Vault',
    budget: 'Budget',
    tools: 'AI Tools',
    settings: 'Settings',
    logout: 'Logout',
    theme: 'App Theme',
    background: 'Background',
    language: 'Language',
    terms: 'Terms of Service',
    privacy: 'Privacy Policy',
    admin: 'Admin',
  },
  fil: {
    goodMorning: 'Magandang Umaga',
    goodAfternoon: 'Magandang Hapon',
    goodEvening: 'Magandang Gabi',
    quickAccess: 'Mabilisang Access',
    customize: 'I-customize',
    done: 'Tapos na',
    dailyReminders: 'Araw-araw na Paalala',
    addTask: 'Magdagdag ng gawain...',
    supportDev: 'Suportahan ang Developer',
    budgetPlanner: 'Budget Planner',
    addTransaction: 'Magdagdag ng Transaksyon',
    income: 'Kita',
    expense: 'Gastusin',
    description: 'Paglalarawan',
    amount: 'Halaga',
    date: 'Petsa',
    category: 'Kategorya',
    addRecord: 'I-save ang Record',
    updateRecord: 'I-update ang Record',
    cancel: 'Kanselahin',
    actions: 'Aksyon',
    totalBalance: 'Kabuuang Balanse',
    spendingHealth: 'Kalusugan ng Paggastos',
    linkVault: 'Link Vault',
    searchLinks: 'Maghanap ng links...',
    save: 'I-save',
    dashboard: 'Dashboard',
    vault: 'Kaban ng Link',
    budget: 'Badyet',
    tools: 'AI Tools',
    settings: 'Settings',
    logout: 'Logout',
    theme: 'Tema ng App',
    background: 'Background',
    language: 'Wika',
    terms: 'Mga Tuntunin',
    privacy: 'Patakaran sa Pribado',
    admin: 'Admin',
  },
  ceb: {
    goodMorning: 'Maayong Buntag',
    goodAfternoon: 'Maayong Hapon',
    goodEvening: 'Maayong Gabii',
    quickAccess: 'Dali nga Access',
    customize: 'Usba',
    done: 'Human na',
    dailyReminders: 'Adlaw-adlaw nga Pahinumdom',
    addTask: 'Dugang buluhaton...',
    supportDev: 'Suporta sa Developer',
    budgetPlanner: 'Plano sa Badyet',
    addTransaction: 'Dugang Transaksyon',
    income: 'Kita',
    expense: 'Gasto',
    description: 'Deskripsyon',
    amount: 'Kantidad',
    date: 'Petsa',
    category: 'Kategorya',
    addRecord: 'I-save ang Rekord',
    updateRecord: 'I-update ang Rekord',
    cancel: 'Kanselahon',
    actions: 'Aksyon',
    totalBalance: 'Total nga Balanse',
    spendingHealth: 'Kahimsog sa Paggasto',
    linkVault: 'Link Vault',
    searchLinks: 'Pangita og links...',
    save: 'I-save',
    dashboard: 'Dashboard',
    vault: 'Link Vault',
    budget: 'Badyet',
    tools: 'AI Tools',
    settings: 'Settings',
    logout: 'Logout',
    theme: 'Tema sa App',
    background: 'Background',
    language: 'Pinulongan',
    terms: 'Mga Termino',
    privacy: 'Pribasiya',
    admin: 'Admin',
  }
};